id: cpp
name: gcc
language: C++

extensions:
  - cpp

acemode: c_cpp

options:
  optim:
    title: Optimization
    type: list
    default: -O0
    candidates:
      - -O0
      - -O1
      - -O2
      - -O3
      - -Os
  std:
    title: Standard
    type: list
    default: -std=c++11
    candidates:
      - -std=c++03
      - -std=gnu++03
      - -std=c++11
      - -std=gnu++11
